name: go project ci pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v5

            - name: set up golang
              uses: actions/setup-go@v5
              with:
                go-version: '1.21.1'
            
            - name: run test
              run: go test ./...
              
            - name: build project 
              run: go build -o app  































































